const menu = [
  {
    id: 1,
    title: "Alison Becker",
    category: "Goalkeeper",
    squadNumber: "No 1",
    img: "https://www.coachesvoice.com/wp-content/uploads/2021/08/AlissonMobile.jpg",
    desc: `Álisson Ramsés Becker, known as Alisson Becker or simply Alisson, is a Brazilian professional footballer who plays as a goalkeeper for Premier League club Liverpool and the Brazil national team`,
  },
  {
    id: 2,
    title: "virgil van dijk",
    category: "Defender",
    squadNumber: "No 4",
    img: "https://cdn.theathletic.com/cdn-cgi/image/width=770,format=auto/https://cdn.theathletic.com/app/uploads/2022/10/16172756/GettyImages-1433863801-scaled-e1665955694152-1024x683.jpg",
    desc: `Virgil van Dijk is a Dutch professional footballer who plays as a centre-back for Premier League club Liverpool and the Netherlands national team. Considered one of the best defenders in the world, Van Dijk is known for his strength, leadership and aerial ability `,
  },
  {
    id: 3,
    title: "Harvey Elliot ",
    category: "Midfielder",
    squadNumber: "No 19",
    img: "https://e0.365dm.com/22/08/2048x1152/skysports-harvey-elliott-liverpool_5861268.jpg",
    desc: `Harvey Daniel James Elliott is an English professional footballer who plays as a central midfielder for Premier League club Liverpool. Having come up through their academy, Elliott made his first-team debut for Fulham in September 2018, becoming the youngest player to play in the EFL Cup, aged 15 years and 174 days`,
  },
  {
    id: 4,
    title: "Darwin Nunez",
    category: "Attcker",
    squadNumber: "No 27",
    img: "http://t0.gstatic.com/licensed-image?q=tbn:ANd9GcSlQFAeHsS-dc70PwGlmzNaKxopfHD1SH-SWWQ8yFhbvwrLXPYWm_NQXKwiT_PExYqONXvj5TJhVTpLqOg",
    desc: `Darwin Gabriel Núñez Ribeiro is a Uruguayan professional footballer who plays as a forward for Premier League club Liverpool and the Uruguay national team. Núñez came through Peñarol's youth academy, being promoted to the first team in 2017. `,
  },
  {
    id: 5,
    title: "Caoimhin Kelleher",
    category: "Goalkeeper",
    squadNumber: "No 62",
    img: "https://i0.wp.com/uzomediatv.com/wp-content/uploads/2022/01/Caoimhin-Kelleher-biography-age-net-worth-wife-parents-siblings-family-profile-salary-Uzomedia-TV.jpg?fit=1024%2C1024&ssl=1",
    desc: `Caoimhín Odhrán Kelleher is an Irish professional footballer who plays as a goalkeeper for Premier League club Liverpool and the Republic of Ireland national team `,
  },
  {
    id: 6,
    title: "Trent Alexander",
    category: "Defender",
    squadNumber: "No 66",
    img: "https://imageio.forbes.com/specials-images/imageserve/62eba5a4ecc08631af373b0d/0x0.jpg?format=jpg&crop=2936,1651,x0,y216,safe&width=1200",
    desc: `Trent John Alexander-Arnold is an English professional footballer who plays as a right-back for Premier League club Liverpool and the England national team. Known for his range of passing, crossing and assists, Alexander-Arnold is widely regarded as one of the best full-backs in world footbal`,
  },
  {
    id: 7,
    title: "Thiago Alcantara",
    category: "Midfielder",
    squadNumber: "No 6 ",
    img: "https://www.coachesvoice.com/wp-content/uploads/2021/06/ThiagoMobile-1.jpg",
    desc: `Thiago Alcântara do Nascimento, Known as Thiago Alcântara or simply Thiago, is a professional footballer who plays as a central midfielder for Premier League club Liverpool and the Spain national team. Known for his accurate passes and technical skills, he is often regarded as one of the best midfielders in the world. `,
  },
  {
    id: 8,
    title: "Luiz Diaz",
    category: "Attcker",
    squadNumber: "No 23",
    img: "https://resources.premierleague.com/premierleague/photo/2022/08/24/166df2ea-ea0f-4b2d-b2e9-6d5984a780fc/Luis-Diaz-Liverpool-.jpg",
    desc: `Luis Fernando Díaz Marulanda is a Colombian professional footballer who plays as a winger for Premier League club Liverpool and the Colombia national team`,
  },
  {
    id: 9,
    title: "Andrew Robertson",
    category: "Defender",
    squadNumber: "No 26",
    img: "https://e0.365dm.com/21/08/2048x1152/skysports-andy-robertson-liverpool_5473477.jpg",
    desc: `Andrew Henry Robertson MBE is a Scottish professional footballer who plays as a left-back for Premier League club Liverpool and captains the Scotland national team. Known for his vision, athleticism and physical power, Robertson is often considered to be one of the best full-backs in the world`,
  },
  {
    id: 10,
    title: "Mo Salah",
    category: "Attcker",
    squadNumber: "No 11",
    img: "https://resources.premierleague.com/premierleague/photos/players/250x250/p118748.png",
    desc: `Mohamed Salah Hamed Mahrous Ghaly, also known as Mo Salah, is an Egyptian professional footballer who plays as a forward for Premier League club Liverpool and captains the Egypt national team.`,
  },
];
export default menu;
